# Set default goal
.DEFAULT_GOAL := help

# Configure shell for safer execution
SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.PHONY: help
help: ## Print comprehensive help for all commands
	@echo "🔧 Convos iOS Development Commands"
	@echo "=================================="
	@echo ""
	@echo "🔑 Secrets Management:"
	@echo "   make secrets         - Generate minimal Secrets.swift (for Dev/Prod builds)"
	@echo "   make secrets-local   - Generate Secrets.swift with IP detection (for Local builds)"
	@echo "   make mock-env        - Generate mock environment for PR builds"
	@echo ""
	@echo "📱 Version Management:"
	@echo "   make version         - Show current version from Xcode project"
	@echo "   make release         - Trigger release workflow (creates PR, tag, promotes to main automatically)"
	@echo ""
	@echo "🔧 Setup & Maintenance:"
	@echo "   make setup           - Setup development environment"
	@echo "   make clean           - Clean all generated files and build artifacts"
	@echo "   make status          - Show project status"
	@echo "   make protobuf        - Generate Swift code from Protocol Buffer definitions"
	@echo ""
	@echo "🌐 Environment Configuration:"
	@echo "   • Local: org.convos.ios-local (local development, auto-detected IP in build phase)"
	@echo "   • Dev: org.convos.ios-preview (TestFlight internal, CI: dev branch)"
	@echo "   • Testnet: org.convos.ios-testnet (testnet infrastructure, XMTP dev network via gateway)"
	@echo "   • Prod: org.convos.ios (App Store, CI: main branch)"
	@echo ""
	@echo "📋 Build Workflow:"
	@echo "   • Local: Secrets auto-generated by build phase with IP detection"
	@echo "   • Dev/Prod: Secrets from .env (locally) or environment variables (CI)"
	@echo "   • Note: Build phase handles Secrets.swift generation automatically"
	@echo ""
	@echo "🔄 Release Process:"
	@echo "   1. Feature branches → dev"
	@echo "   2. Create release: make release (triggers CI workflow, creates PR)"
	@echo "   3. Merge the release PR (CI auto-creates tag, GitHub Release, and promotes to main)"
	@echo "   4. Bitrise builds from main → App Store"

.PHONY: setup
setup: ## Setup dependencies and developer environment
	./Scripts/setup.sh

.PHONY: secrets
secrets: ## Generate Secrets.swift (auto-detects CI environment)
	@if [ -n "$$CI" ] || [ -n "$$BITRISE_BUILD_NUMBER" ]; then \
		echo "🔧 CI/CD environment detected, generating minimal secrets..."; \
		./Scripts/generate-secrets-secure.sh; \
	else \
		echo "🏠 Local environment detected, generating minimal secrets..."; \
		echo "💡 Tip: Use 'make secrets-local' for IP detection, or just build - the build phase handles it automatically"; \
		./Scripts/generate-secrets-secure.sh; \
	fi

.PHONY: secrets-local
secrets-local: ## Generate Secrets.swift with auto-detected local IP
	./Scripts/generate-secrets-local.sh

.PHONY: ensure-secrets
ensure-secrets: ## Ensure minimal Secrets.swift exists
	./Scripts/generate-secrets-local.sh --ensure-only

.PHONY: mock-env
mock-env: ## Generate a mock .env file for PR builds
	./Scripts/generate-mock-env.sh

.PHONY: version
version: ## Get current version from Xcode project
	./Scripts/get-version.sh

.PHONY: clean
clean: ## Clean generated files
	rm -f Convos/Config/Secrets.swift
	rm -rf build/
	rm -rf DerivedData/
	rm -rf *.xcarchive
	rm -rf *.ipa

.PHONY: status
status: ## Show project status (version, secrets, git)
	@echo "📱 Project Status"
	@echo "=================="
	@echo "Version: $$(./Scripts/get-version.sh)"
	@echo "Build Number: Managed by Bitrise (BITRISE_BUILD_NUMBER)"
	@echo "Secrets: $$(if [ -f Convos/Config/Secrets.swift ]; then echo "✅ Generated"; else echo "❌ Missing"; fi)"
	@echo "Git: $$(git rev-parse --abbrev-ref HEAD) ($$(git rev-parse --short HEAD))"
	@echo "Environment: $$(if [ -f .env ]; then echo "✅ .env exists"; else echo "❌ No .env"; fi)"
	@echo ""
	@echo "🌍 Available Schemes:"
	@echo "   • Local: Auto-generates secrets with IP detection in build phase"
	@echo "   • Dev: Uses minimal secrets from .env or 'make secrets'"
	@echo "   • Testnet: Uses secrets from .env (CONVOS_API_BASE_URL required)"
	@echo "   • Prod: Uses minimal secrets from .env or 'make secrets'"

.PHONY: protobuf
protobuf: ## Generate Swift code from Protocol Buffer definitions
	@echo "🔧 Generating Swift code from Protocol Buffer definitions..."
	@ConvosCore/Sources/ConvosCore/Protobuf\ Models/proto/generate_swift.sh

.PHONY: release
release: ## Trigger the Create Release workflow on GitHub Actions
	@if ! command -v gh &> /dev/null; then \
		echo "❌ GitHub CLI (gh) is not installed. Install with: brew install gh"; \
		exit 1; \
	fi
	@if ! gh auth status &> /dev/null 2>&1; then \
		echo "❌ GitHub CLI is not authenticated. Run: gh auth login"; \
		exit 1; \
	fi
	@CURRENT_VERSION=$$(./Scripts/get-version.sh 2>/dev/null || echo "unknown"); \
	echo "📱 Create Release"; \
	echo "=================="; \
	echo ""; \
	echo "Current version: $$CURRENT_VERSION"; \
	echo ""; \
	read -p "Enter new version (e.g., 1.2.0 or 1.2.0-dev.123): " NEW_VERSION; \
	if [ -z "$$NEW_VERSION" ]; then \
		echo "❌ No version provided"; \
		exit 1; \
	fi; \
	echo ""; \
	echo "This will trigger the release workflow on GitHub Actions:"; \
	echo "  1. Create release/$$NEW_VERSION branch from dev"; \
	echo "  2. Bump MARKETING_VERSION in Xcode project"; \
	echo "  3. Open a PR to dev"; \
	echo ""; \
	echo "After you merge the PR, CI will automatically:"; \
	echo "  - Create the git tag"; \
	echo "  - Generate release notes and create a GitHub Release"; \
	echo "  - Fast-forward main to dev (production releases only)"; \
	echo "  - Bitrise builds and deploys to TestFlight"; \
	echo ""; \
	read -p "Continue? (y/N): " CONFIRM; \
	if [[ ! "$$CONFIRM" =~ ^[Yy]$$ ]]; then \
		echo "❌ Release cancelled"; \
		exit 1; \
	fi; \
	echo ""; \
	echo "🚀 Triggering release workflow..."; \
	gh workflow run "Create Release" --field version="$$NEW_VERSION"; \
	echo ""; \
	echo "✅ Workflow triggered! Watch progress at:"; \
	echo "   https://github.com/$$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows/create-release.yml"
