import Foundation

/// Produces the single-inbox XMTP archive written into the backup bundle.
///
/// The real implementation wraps the live XMTPiOS client's `createArchive`;
/// tests inject a deterministic stub. Each call is expected to produce a
/// standalone encrypted archive sealed with the per-bundle `encryptionKey`
/// — a fresh 32-byte CSPRNG value generated by `BackupManager`, not the
/// identity's `databaseKey`, so historical bundles stay cryptographically
/// isolated from one another.
public protocol BackupArchiveProviding: Sendable {
    /// Writes the archive to `path` and returns its time range so the bundle
    /// metadata can record it without re-opening the archive.
    func createArchive(at path: URL, encryptionKey: Data) async throws -> XMTPArchiveStats
}

/// Summary of a single-inbox XMTP archive suitable for the bundle metadata.
public struct XMTPArchiveStats: Sendable, Equatable {
    public let startNs: Int64?
    public let endNs: Int64?
    public let installationId: String

    public init(startNs: Int64?, endNs: Int64?, installationId: String) {
        self.startNs = startNs
        self.endNs = endNs
        self.installationId = installationId
    }
}
