// swiftlint:disable all
//
// This file is regenerated by Scripts/build-phases/copy-env-config-main-app.sh
// on every build. The committed placeholder exists only so the
// NotificationService target's file-synchronized group registers
// BuildInfo at Xcode planning time on a fresh CI checkout. Do not
// edit by hand — your changes will be overwritten on next build.
//
enum BuildInfo {
    static let commitHash: String = "unknown"
}
// swiftlint:enable all
