// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: convo_request.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ConvoRequest is sent via the 1:1 back channel between two members'
/// group inbox IDs to initiate a new conversation (DM or group spinoff).
///
/// For DMs: invite_slug is absent. The receiver creates a new locked
/// conversation and adds the sender.
///
/// For group spinoffs (phase 2): invite_slug is present. The receiver
/// joins the sender's existing group via the invite.
public struct ConvoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The sender's fresh inbox ID for the new conversation (hex string).
  public var newInboxID: String = String()

  /// Random tag to correlate this request with the resulting conversation.
  /// Stored in conversation metadata for origin context display.
  public var convoTag: String = String()

  /// The conversation ID where both members met (for consent checks).
  public var originConversationID: String = String()

  /// If present, an invite slug for joining an existing group (spinoff).
  /// If absent, the receiver creates a new 1:1 conversation (DM).
  public var inviteSlug: String {
    get {_inviteSlug ?? String()}
    set {_inviteSlug = newValue}
  }
  /// Returns true if `inviteSlug` has been explicitly set.
  public var hasInviteSlug: Bool {self._inviteSlug != nil}
  /// Clears the value of `inviteSlug`. Subsequent reads from it will return its default value.
  public mutating func clearInviteSlug() {self._inviteSlug = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _inviteSlug: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension ConvoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ConvoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_inbox_id\0\u{3}convo_tag\0\u{3}origin_conversation_id\0\u{3}invite_slug\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.newInboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.convoTag) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.originConversationID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._inviteSlug) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.newInboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.newInboxID, fieldNumber: 1)
    }
    if !self.convoTag.isEmpty {
      try visitor.visitSingularStringField(value: self.convoTag, fieldNumber: 2)
    }
    if !self.originConversationID.isEmpty {
      try visitor.visitSingularStringField(value: self.originConversationID, fieldNumber: 3)
    }
    try { if let v = self._inviteSlug {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ConvoRequest, rhs: ConvoRequest) -> Bool {
    if lhs.newInboxID != rhs.newInboxID {return false}
    if lhs.convoTag != rhs.convoTag {return false}
    if lhs.originConversationID != rhs.originConversationID {return false}
    if lhs._inviteSlug != rhs._inviteSlug {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
