#!/bin/bash
set -e

# Part 1: Generate Secrets.swift for Local and Dev builds (App target only)
if [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Local" ]; then
    echo "🏠 Local build detected - generating secrets with auto-detected IP"
    
    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"
    
    # Get the first routable IPv4 address (excluding link-local/APIPA addresses)
    # First try to get a public IP (not in private ranges)
    LOCAL_IP=$(ifconfig | grep -E "inet [0-9]+" | grep -v "127\\." | grep -v "169\\.254\\." | grep -v "10\\." | grep -v "172\\.1[6-9]\\." | grep -v "172\\.2[0-9]\\." | grep -v "172\\.3[0-1]\\." | grep -v "192\\.168\\." | head -1 | awk '{print $2}')
    # If no public IP, get the first private network IP (but not link-local)
    if [ -z "$LOCAL_IP" ]; then
        LOCAL_IP=$(ifconfig | grep -E "inet [0-9]+" | grep -v "127\\." | grep -v "169\\.254\\." | head -1 | awk '{print $2}')
    fi
    
    if [ -z "$LOCAL_IP" ]; then
        echo "❌ Could not detect local IP address"
        exit 1
    fi
    
    echo "✅ Detected local IP"
    
    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"
    
    # Start generating Secrets.swift
    cat > "$SECRETS_FILE" << 'HEADER_EOF'
import Foundation

// WARNING:
// This code is generated by the build phase for Local development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// For Local builds, the IP addresses are auto-detected from your network interfaces.
// For other environments, edit the .env file and run ./Scripts/generate-secrets.sh

// swiftlint:disable all

/// Secrets are generated automatically for Local development
enum Secrets {
HEADER_EOF

    # Check if .env has custom values first, otherwise auto-detect
    CONVOS_API_BASE_URL=""
    XMTP_CUSTOM_HOST=""
    
    if [ -f "${SRCROOT}/.env" ]; then
        # Check for uncommented values in .env
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
        XMTP_CUSTOM_HOST=$(grep -v '^#' "${SRCROOT}/.env" | grep '^XMTP_CUSTOM_HOST=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    # Use .env values if present, otherwise auto-detect
    if [ -n "$CONVOS_API_BASE_URL" ]; then
        echo "🔧 Using CONVOS_API_BASE_URL from .env"
        echo "    static let CONVOS_API_BASE_URL = \\"$CONVOS_API_BASE_URL\\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Auto-detecting CONVOS_API_BASE_URL"
        echo "    static let CONVOS_API_BASE_URL = \\"http://$LOCAL_IP:4000/api\\"" >> "$SECRETS_FILE"
    fi

    if [ -n "$XMTP_CUSTOM_HOST" ]; then
        echo "🔧 Using XMTP_CUSTOM_HOST from .env"
        echo "    static let XMTP_CUSTOM_HOST = \\"$XMTP_CUSTOM_HOST\\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Auto-detecting XMTP_CUSTOM_HOST"
        echo "    static let XMTP_CUSTOM_HOST = \\"$LOCAL_IP\\"" >> "$SECRETS_FILE"
    fi
    
    # Add other secrets from .env if available
    if [ -f "${SRCROOT}/.env" ]; then
        echo "📋 Adding additional secrets from .env file..."
        
        # Process .env file: skip comments, empty lines, and IP-related keys (since we handled them above), then format as Swift
        sed -n '/^[^#]/p' "${SRCROOT}/.env" | grep '=' | grep -v '^CONVOS_API_BASE_URL' | grep -v '^XMTP_CUSTOM_HOST' | sed 's/^\\([^=]*\\)=\\(.*\\)$/    static let \\1 = "\\2"/' | sed 's/""\\(.*\\)""/"\\1"/' >> "$SECRETS_FILE"
    fi
    
    # Close the enum
    cat >> "$SECRETS_FILE" << 'FOOTER_EOF'
}

// swiftlint:enable all
FOOTER_EOF
    
    echo "🏁 Generated Secrets.swift with auto-detected IP"

# Part 1b: Generate Secrets.swift for Dev builds (read Firebase token from .env)
elif [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Dev" ]; then
    echo "🔧 Dev build detected - generating secrets from .env"
    
    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"
    
    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"
    
    # Read Firebase debug token from .env
    FIREBASE_TOKEN=""
    CONVOS_API_BASE_URL=""
    if [ -f "${SRCROOT}/.env" ]; then
        FIREBASE_TOKEN=$(grep -v '^#' "${SRCROOT}/.env" | grep '^FIREBASE_APP_CHECK_DEBUG_TOKEN=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)

        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi
    
    if [ -n "$FIREBASE_TOKEN" ]; then
        echo "✅ Found Firebase debug token in .env"
    else
        echo "⚠️  No Firebase debug token in .env - you may need to register tokens manually"
    fi
    
    # Generate Secrets.swift for Dev
    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for Dev development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.

// swiftlint:disable all

/// Secrets are generated automatically for Dev development
enum Secrets {
    static let CONVOS_API_BASE_URL = "$CONVOS_API_BASE_URL"
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let SENTRY_DSN = ""
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = "$FIREBASE_TOKEN"
}

// swiftlint:enable all
EOF
    
    echo "🏁 Generated Secrets.swift for Dev"
fi

# Part 2: Copy config file (existing functionality)
CONFIG_SOURCE="${SRCROOT}/Convos/Config/${CONFIG_FILE}"
CONFIG_DEST="${TARGET_BUILD_DIR}/${WRAPPER_NAME}/config.json"

if [ ! -f "$CONFIG_SOURCE" ]; then
    echo "error: Config file not found: $CONFIG_SOURCE (CONFIG_FILE=$CONFIG_FILE)"
    exit 1
fi

echo "📋 Copying $CONFIG_FILE to app bundle"
cp "$CONFIG_SOURCE" "$CONFIG_DEST"
echo "✅ Config copied successfully"
