#!/bin/bash
set -e

source "${SRCROOT}/Scripts/secrets-utils.sh"

# Part 1: Generate Secrets.swift for App Clip (Local and Dev builds)
if [ "$CONFIGURATION" = "Local" ] || [ "$CONFIGURATION" = "Dev" ]; then
    echo "🔧 $CONFIGURATION build detected - generating App Clip secrets from .env"

    SECRETS_FILE="${SRCROOT}/ConvosAppClip/Config/Secrets.swift"
    mkdir -p "${SRCROOT}/ConvosAppClip/Config"

    # Firebase debug token: cached .env first, else 1Password ("Convos" vault); empty in CI.
    FIREBASE_TOKEN="$(resolve_firebase_debug_token "${SRCROOT}/.env")"
    CONVOS_API_BASE_URL=""
    POSTHOG_API_KEY=""
    if [ -f "${SRCROOT}/.env" ]; then
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
        POSTHOG_API_KEY=$(grep -v '^#' "${SRCROOT}/.env" | grep '^POSTHOG_API_KEY=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    if [ -n "$FIREBASE_TOKEN" ]; then
        echo "✅ Resolved Firebase debug token (1Password or .env cache)"
    else
        echo "⚠️  No Firebase debug token from 1Password or .env"
    fi

    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for $CONFIGURATION.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.

// swiftlint:disable all

enum Secrets {
    static let CONVOS_API_BASE_URL = "$CONVOS_API_BASE_URL"
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let SENTRY_DSN = ""
    static let POSTHOG_API_KEY = "$POSTHOG_API_KEY"
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = "$FIREBASE_TOKEN"
}

// swiftlint:enable all
EOF

    echo "🏁 Generated App Clip Secrets.swift"

# Part 1b: Generate Secrets.swift for LOCAL App Clip Prod builds (Release
# config). GATED LOCAL-ONLY (mirrors the CI guard at Makefile:50): in CI, `make
# secrets` runs generate-secrets-secure.sh first and injects the real analytics
# keys, so this build phase must NOT clobber that output — the Release branch is
# skipped when $CI or $BITRISE_BUILD_NUMBER is set. Locally we force the backend
# URL and XMTP host EMPTY so ConfigManager falls back to the prod
# source-of-truth in config.prod.json. Values are NEVER read from .env here
# (that local dev backend leak is what this PR fixes); every field is empty.
elif [ "$CONFIGURATION" = "Release" ] && [ -z "$CI" ] && [ -z "$BITRISE_BUILD_NUMBER" ]; then
    echo "🚀 Local Prod (Release) App Clip build detected - resolving backend from config.prod.json"

    SECRETS_FILE="${SRCROOT}/ConvosAppClip/Config/Secrets.swift"
    mkdir -p "${SRCROOT}/ConvosAppClip/Config"

    cat > "$SECRETS_FILE" << EOF_PROD
import Foundation

// WARNING:
// This code is generated by the build phase for local Prod (Release) builds.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// Backend URL and XMTP host are intentionally empty: ConfigManager resolves
// them from config.prod.json (the prod source-of-truth). Values are NOT read
// from .env here, to prevent a local dev backend from leaking into Prod.

// swiftlint:disable all

enum Secrets {
    static let CONVOS_API_BASE_URL = ""
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let SENTRY_DSN = ""
    static let POSTHOG_API_KEY = ""
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = ""
}

// swiftlint:enable all
EOF_PROD

    echo "🏁 Generated App Clip local Prod Secrets.swift"
fi

# Part 2: Copy config file to app bundle
if [[ "$CONFIG_FILE" = /* ]]; then
    CONFIG_SOURCE="$CONFIG_FILE"
else
    CONFIG_SOURCE="${SRCROOT}/Convos/Config/${CONFIG_FILE}"
fi

CONFIG_DEST="${CODESIGNING_FOLDER_PATH}/config.json"

if [ ! -f "$CONFIG_SOURCE" ]; then
    echo "error: Config file not found: $CONFIG_SOURCE (CONFIG_FILE=$CONFIG_FILE)"
    exit 1
fi

echo "📋 Copying config file to app bundle"
cp "$CONFIG_SOURCE" "$CONFIG_DEST"
echo "✅ Config copied successfully"
