#!/bin/bash
set -e

source "${SRCROOT}/Scripts/secrets-utils.sh"

# Part 1: Generate Secrets.swift for the Share Extension (Local and Dev builds).
# The extension runs in its own process and cannot read the main app's
# Secrets.swift or its GACAppCheckDebugToken, so it needs its own copy of the
# Firebase App Check debug token to authorize against its own Firebase app.
# Secrets.swift is a compiled source of the target, so it must exist for every
# configuration (CI archives PR Preview with a clean checkout). The debug token
# is only resolved for Local/Dev; other configs get an empty value.
echo "🔧 $CONFIGURATION build - generating Share Extension secrets"

SECRETS_FILE="${SRCROOT}/ShareExtension/Config/Secrets.swift"
mkdir -p "${SRCROOT}/ShareExtension/Config"

FIREBASE_TOKEN=""
if [ "$CONFIGURATION" = "Local" ] || [ "$CONFIGURATION" = "Dev" ]; then
    # Firebase debug token: cached .env first, else 1Password ("Convos" vault); empty in CI.
    FIREBASE_TOKEN="$(resolve_firebase_debug_token "${SRCROOT}/.env")"

    if [ -n "$FIREBASE_TOKEN" ]; then
        echo "✅ Resolved Firebase debug token (1Password or .env cache)"
    else
        echo "⚠️  No Firebase debug token from 1Password or .env"
    fi
fi

    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for $CONFIGURATION.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.

// swiftlint:disable all

enum Secrets {
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = "$FIREBASE_TOKEN"
}

// swiftlint:enable all
EOF

echo "🏁 Generated Share Extension Secrets.swift"

# Part 2: Copy the environment's config.json into the extension bundle. The
# extension's ConfigManager reads config.json from its own bundle; CONFIG_FILE
# is provided per-config by the environment xcconfig (mirrors the main app).
if [[ "$CONFIG_FILE" = /* ]]; then
    CONFIG_SOURCE="$CONFIG_FILE"
else
    CONFIG_SOURCE="${SRCROOT}/Convos/Config/${CONFIG_FILE}"
fi
CONFIG_DEST="${CODESIGNING_FOLDER_PATH}/config.json"

if [ ! -f "$CONFIG_SOURCE" ]; then
    echo "error: Config file not found: $CONFIG_SOURCE (CONFIG_FILE=$CONFIG_FILE)"
    exit 1
fi

echo "📋 Copying $CONFIG_FILE to the extension bundle"
cp "$CONFIG_SOURCE" "$CONFIG_DEST"
echo "✅ Config copied"
