#!/bin/bash
set -e

source "${SRCROOT}/Scripts/secrets-utils.sh"
GIT_SHA=$(get_git_commit_sha "${SRCROOT}")

# Generate BuildInfo.swift for the NotificationService extension
if [ "$TARGET_NAME" = "NotificationService" ]; then
    mkdir -p "${SRCROOT}/NotificationService"
    BUILD_INFO_PATH="${SRCROOT}/NotificationService/BuildInfo.swift"
    BUILD_INFO_CONTENT="// swiftlint:disable all
//
// This file is regenerated by Scripts/build-phases/copy-env-config-main-app.sh
// on every build. The committed placeholder exists only so the
// NotificationService target's file-synchronized group registers
// BuildInfo at Xcode planning time on a fresh CI checkout. Do not
// edit by hand — your changes will be overwritten on next build.
//
enum BuildInfo {
    static let commitHash: String = \"$(swift_escape "$GIT_SHA")\"
}
// swiftlint:enable all"
    if [ ! -f "$BUILD_INFO_PATH" ] || [ "$(cat "$BUILD_INFO_PATH")" != "$BUILD_INFO_CONTENT" ]; then
        printf '%s\n' "$BUILD_INFO_CONTENT" > "$BUILD_INFO_PATH"
        echo "🏁 Generated BuildInfo.swift for NotificationService (commit: $GIT_SHA)"
    else
        echo "✅ BuildInfo.swift already up-to-date (commit: $GIT_SHA)"
    fi
fi

# Part 1: Generate Secrets.swift for Local and Dev builds (App target only)
if [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Local" ]; then
    echo "🏠 Local build detected - generating secrets with auto-detected IP"
    
    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"
    
    # Get the first routable IPv4 address (excluding link-local/APIPA addresses)
    # First try to get a public IP (not in private ranges)
    LOCAL_IP=$(ifconfig | grep -E "inet [0-9]+" | grep -v "127\\." | grep -v "169\\.254\\." | grep -v "10\\." | grep -v "172\\.1[6-9]\\." | grep -v "172\\.2[0-9]\\." | grep -v "172\\.3[0-1]\\." | grep -v "192\\.168\\." | head -1 | awk '{print $2}')
    # If no public IP, get the first private network IP (but not link-local)
    if [ -z "$LOCAL_IP" ]; then
        LOCAL_IP=$(ifconfig | grep -E "inet [0-9]+" | grep -v "127\\." | grep -v "169\\.254\\." | head -1 | awk '{print $2}')
    fi
    
    if [ -z "$LOCAL_IP" ]; then
        echo "❌ Could not detect local IP address"
        exit 1
    fi
    
    echo "✅ Detected local IP"
    
    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"
    
    # Start generating Secrets.swift
    cat > "$SECRETS_FILE" << 'HEADER_EOF'
import Foundation

// WARNING:
// This code is generated by the build phase for Local development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// For Local builds, the IP addresses are auto-detected from your network interfaces.
// For other environments, edit the .env file and run ./Scripts/generate-secrets.sh

// swiftlint:disable all

/// Secrets are generated automatically for Local development
enum Secrets {
HEADER_EOF

    # Check if .env has custom values first, otherwise auto-detect
    CONVOS_API_BASE_URL=""
    XMTP_CUSTOM_HOST=""
    POSTHOG_API_KEY=""

    if [ -f "${SRCROOT}/.env" ]; then
        # Check for uncommented values in .env
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
        XMTP_CUSTOM_HOST=$(grep -v '^#' "${SRCROOT}/.env" | grep '^XMTP_CUSTOM_HOST=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
        POSTHOG_API_KEY=$(grep -v '^#' "${SRCROOT}/.env" | grep '^POSTHOG_API_KEY=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    # Use .env values if present, otherwise auto-detect
    if [ -n "$CONVOS_API_BASE_URL" ]; then
        echo "🔧 Using CONVOS_API_BASE_URL from .env"
        echo "    static let CONVOS_API_BASE_URL = \"$CONVOS_API_BASE_URL\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Auto-detecting CONVOS_API_BASE_URL"
        echo "    static let CONVOS_API_BASE_URL = \"http://$LOCAL_IP:4000/api\"" >> "$SECRETS_FILE"
    fi

    if [ -n "$XMTP_CUSTOM_HOST" ]; then
        echo "🔧 Using XMTP_CUSTOM_HOST from .env"
        echo "    static let XMTP_CUSTOM_HOST = \"$XMTP_CUSTOM_HOST\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Auto-detecting XMTP_CUSTOM_HOST"
        echo "    static let XMTP_CUSTOM_HOST = \"$LOCAL_IP\"" >> "$SECRETS_FILE"
    fi

    echo "    static let POSTHOG_API_KEY = \"$POSTHOG_API_KEY\"" >> "$SECRETS_FILE"
    echo "    static let GIT_COMMIT_SHA: String = \"$(swift_escape "$GIT_SHA")\"" >> "$SECRETS_FILE"

    # Populate the Firebase token cache from the "Convos" 1Password vault if .env
    # has none (cache-first: no-op when .env already has a token, in CI, or when op
    # is unavailable) so the .env dump below can emit it.
    resolve_firebase_debug_token "${SRCROOT}/.env" >/dev/null

    # Add other secrets from .env if available
    if [ -f "${SRCROOT}/.env" ]; then
        echo "📋 Adding additional secrets from .env file..."

        # Process .env file: skip comments, empty lines, and keys handled above, then format as Swift
        sed -n '/^[^#]/p' "${SRCROOT}/.env" | grep '=' | grep -v '^CONVOS_API_BASE_URL' | grep -v '^XMTP_CUSTOM_HOST' | grep -v '^POSTHOG_API_KEY' | grep -v '^GIT_COMMIT_SHA' | sed 's/^\([^=]*\)=\(.*\)$/    static let \1 = "\2"/' | sed 's/""\(.*\)""/"\1"/' >> "$SECRETS_FILE"
    fi
    
    # Close the enum
    cat >> "$SECRETS_FILE" << 'FOOTER_EOF'
}

// swiftlint:enable all
FOOTER_EOF
    
    echo "🏁 Generated Secrets.swift with auto-detected IP"

# Part 1b: Generate Secrets.swift for Dev builds (read Firebase token from .env)
elif [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Dev" ]; then
    echo "🔧 Dev build detected - generating secrets from .env"

    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"

    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"

    # Firebase debug token: cached .env first, else the team "Convos" 1Password
    # vault on a cache miss. Always empty in CI. See resolve_firebase_debug_token
    # in Scripts/secrets-utils.sh.
    FIREBASE_TOKEN="$(resolve_firebase_debug_token "${SRCROOT}/.env")"
    CONVOS_API_BASE_URL=""
    AGENT_DEBUG_JWKS=""
    POSTHOG_API_KEY=""
    SENTRY_DSN=""
    if [ -f "${SRCROOT}/.env" ]; then
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)

        AGENT_DEBUG_JWKS=$(grep -v '^#' "${SRCROOT}/.env" | grep '^AGENT_DEBUG_JWKS=' | cut -d'=' -f2- | sed -e "s/^'//" -e "s/'$//" || true)
        POSTHOG_API_KEY=$(grep -v '^#' "${SRCROOT}/.env" | grep '^POSTHOG_API_KEY=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)

        SENTRY_DSN=$(grep -v '^#' "${SRCROOT}/.env" | grep '^SENTRY_DSN=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    if [ -n "$FIREBASE_TOKEN" ]; then
        echo "✅ Resolved Firebase debug token (1Password or .env cache)"
    else
        echo "⚠️  No Firebase debug token from 1Password or .env - you may need to register one (run /firebase-token)"
    fi

    if [ -n "$AGENT_DEBUG_JWKS" ]; then
        echo "✅ Found AGENT_DEBUG_JWKS in .env (DEBUG attestation override active)"
    fi

    if [ -n "$SENTRY_DSN" ]; then
        echo "✅ Found SENTRY_DSN in .env (Sentry enabled for this Dev build)"
    fi

    ESCAPED_AGENT_DEBUG_JWKS=$(swift_escape "$AGENT_DEBUG_JWKS")

    # Generate Secrets.swift for Dev
    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for Dev development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.

// swiftlint:disable all

/// Secrets are generated automatically for Dev development
enum Secrets {
    static let CONVOS_API_BASE_URL = "$CONVOS_API_BASE_URL"
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let POSTHOG_API_KEY = "$POSTHOG_API_KEY"
    static let SENTRY_DSN = "$(swift_escape "$SENTRY_DSN")"
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = "$FIREBASE_TOKEN"
    static let GIT_COMMIT_SHA: String = "$(swift_escape "$GIT_SHA")"
    static let AGENT_DEBUG_JWKS: String = "$ESCAPED_AGENT_DEBUG_JWKS"
}

// swiftlint:enable all
EOF

    echo "🏁 Generated Secrets.swift for Dev"

# Part 1c: Generate Secrets.swift for LOCAL Prod builds (the "Convos (Prod)"
# scheme uses the "Release" configuration). Local Prod builds skip `make
# secrets`, so without this branch a stale Local-build Secrets.swift (with an
# auto-detected LAN/Tailscale IP) would be reused and leak into the Prod app.
#
# This branch is GATED LOCAL-ONLY (mirrors the CI guard at Makefile:50). In CI,
# `make secrets` runs `generate-secrets-secure.sh` first and injects the real
# analytics keys; this build phase must NOT clobber that output, so the Release
# branch is skipped whenever $CI or $BITRISE_BUILD_NUMBER is set.
#
# Locally we emit the SAME all-empty shape generate-secrets-secure.sh produces
# for a Release build with no CI-injected secrets: backend URL and XMTP host
# EMPTY so ConfigManager falls back to the prod source-of-truth in
# config.prod.json (api.prod.convos.xyz, production XMTP network). We never read
# these from .env — that is exactly the dev-backend leak this PR fixes. The
# Firebase debug token is irrelevant in prod (forced nil in ConvosApp.swift when
# environment.isProduction), so empty is correct.
elif [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Release" ] && [ -z "$CI" ] && [ -z "$BITRISE_BUILD_NUMBER" ]; then
    echo "🚀 Local Prod (Release) build detected - resolving backend from config.prod.json"

    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"

    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"

    # Firebase debug token: cached .env first, else 1Password ("Convos" vault); empty in CI.
    FIREBASE_TOKEN="$(resolve_firebase_debug_token "${SRCROOT}/.env")"

    # Generate Secrets.swift for Prod. Every override is empty (matching the CI
    # generate-secrets-secure.sh output for a local Release with no injected
    # secrets); only GIT_COMMIT_SHA is populated.
    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for local Prod (Release) builds.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// Backend URL and XMTP host are intentionally empty: ConfigManager resolves
// them from config.prod.json (the prod source-of-truth). Values are NOT read
// from .env here, to prevent a local dev backend from leaking into Prod.

// swiftlint:disable all

/// Secrets are generated automatically for local Prod (Release) builds
enum Secrets {
    static let CONVOS_API_BASE_URL = ""
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let POSTHOG_API_KEY = ""
    static let SENTRY_DSN = ""
    static let FIREBASE_APP_CHECK_DEBUG_TOKEN = "$FIREBASE_TOKEN"
    static let GIT_COMMIT_SHA: String = "$(swift_escape "$GIT_SHA")"
    static let AGENT_DEBUG_JWKS: String = ""
}

// swiftlint:enable all
EOF

    echo "🏁 Generated Secrets.swift for local Prod"

fi

# Part 2: Copy config file (existing functionality)
CONFIG_SOURCE="${SRCROOT}/Convos/Config/${CONFIG_FILE}"
CONFIG_DEST="${TARGET_BUILD_DIR}/${WRAPPER_NAME}/config.json"

if [ ! -f "$CONFIG_SOURCE" ]; then
    echo "error: Config file not found: $CONFIG_SOURCE (CONFIG_FILE=$CONFIG_FILE)"
    exit 1
fi

echo "📋 Copying $CONFIG_FILE to app bundle"
cp "$CONFIG_SOURCE" "$CONFIG_DEST"
echo "✅ Config copied successfully"
