// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: invite.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// InvitePayload represents the core invite data
public struct InvitePayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The encrypted conversation id (stored as raw bytes for compactness)
  public var conversationToken: Data = Data()

  /// The creator's inbox ID as raw bytes (hex-decoded for compactness)
  /// Required for: 1) conversation token decryption AAD, 2) joiner to know who to DM
  public var creatorInboxID: Data = Data()

  /// The tag to mark which conversation this corresponds to, lives in `ConversationCustomMetadata`
  public var tag: String = String()

  /// optional conversation metadata
  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var description_p: String {
    get {return _description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var imageURL: String {
    get {return _imageURL ?? String()}
    set {_imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {return self._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {self._imageURL = nil}

  /// Compact timestamp encoding: Unix timestamp in seconds (8 bytes fixed)
  /// More compact than google.protobuf.Timestamp which uses two varints
  public var conversationExpiresAtUnix: Int64 {
    get {return _conversationExpiresAtUnix ?? 0}
    set {_conversationExpiresAtUnix = newValue}
  }
  /// Returns true if `conversationExpiresAtUnix` has been explicitly set.
  public var hasConversationExpiresAtUnix: Bool {return self._conversationExpiresAtUnix != nil}
  /// Clears the value of `conversationExpiresAtUnix`. Subsequent reads from it will return its default value.
  public mutating func clearConversationExpiresAtUnix() {self._conversationExpiresAtUnix = nil}

  /// Compact invite expiration: Unix timestamp in seconds (8 bytes fixed)
  public var expiresAtUnix: Int64 {
    get {return _expiresAtUnix ?? 0}
    set {_expiresAtUnix = newValue}
  }
  /// Returns true if `expiresAtUnix` has been explicitly set.
  public var hasExpiresAtUnix: Bool {return self._expiresAtUnix != nil}
  /// Clears the value of `expiresAtUnix`. Subsequent reads from it will return its default value.
  public mutating func clearExpiresAtUnix() {self._expiresAtUnix = nil}

  /// Whether the invite should expire after being used once
  public var expiresAfterUse: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _imageURL: String? = nil
  fileprivate var _conversationExpiresAtUnix: Int64? = nil
  fileprivate var _expiresAtUnix: Int64? = nil
}

/// SignedInvite represents an invite with its cryptographic signature
public struct SignedInvite: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The invite payload containing the actual invite data, stored as bytes
  /// to preserve the exact serialization that was signed. This ensures signatures
  /// remain valid even if the protobuf schema changes (since protobuf serialization
  /// is not canonical).
  public var payload: Data = Data()

  /// The cryptographic signature (typically 65 bytes for ECDSA with recovery)
  public var signature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension InvitePayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "InvitePayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}conversationToken\0\u{3}creator_inbox_id\0\u{1}tag\0\u{1}name\0\u{1}description\0\u{1}imageURL\0\u{1}conversationExpiresAtUnix\0\u{1}expiresAtUnix\0\u{1}expiresAfterUse\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.conversationToken) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.creatorInboxID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._imageURL) }()
      case 7: try { try decoder.decodeSingularSFixed64Field(value: &self._conversationExpiresAtUnix) }()
      case 8: try { try decoder.decodeSingularSFixed64Field(value: &self._expiresAtUnix) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.expiresAfterUse) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.conversationToken.isEmpty {
      try visitor.visitSingularBytesField(value: self.conversationToken, fieldNumber: 1)
    }
    if !self.creatorInboxID.isEmpty {
      try visitor.visitSingularBytesField(value: self.creatorInboxID, fieldNumber: 2)
    }
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 3)
    }
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._imageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._conversationExpiresAtUnix {
      try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._expiresAtUnix {
      try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 8)
    } }()
    if self.expiresAfterUse != false {
      try visitor.visitSingularBoolField(value: self.expiresAfterUse, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: InvitePayload, rhs: InvitePayload) -> Bool {
    if lhs.conversationToken != rhs.conversationToken {return false}
    if lhs.creatorInboxID != rhs.creatorInboxID {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs._name != rhs._name {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._imageURL != rhs._imageURL {return false}
    if lhs._conversationExpiresAtUnix != rhs._conversationExpiresAtUnix {return false}
    if lhs._expiresAtUnix != rhs._expiresAtUnix {return false}
    if lhs.expiresAfterUse != rhs.expiresAfterUse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SignedInvite: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SignedInvite"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}payload\0\u{1}signature\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 1)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SignedInvite, rhs: SignedInvite) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
