// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: conversation_custom_metadata.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ParticipationMode governs how much the agents in a conversation speak. The
/// mode belongs to the conversation, not to one agent: a room holding several
/// agents has a single mode that governs all of them, and an agent that joins
/// later inherits it from the synced group state.
///
/// Carried in appData rather than a message so it rides the group-metadata
/// rails: new members read the current mode on join, and MLS metadata's
/// last-writer-wins resolution settles two members changing it at once.
public nonisolated enum ParticipationMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never written; an unset mode is the product default
  case unspecified // = 0
  case speakFreely // = 1
  case mentionsOnly // = 2
  case paused // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .speakFreely
    case 2: self = .mentionsOnly
    case 4: self = .paused
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .speakFreely: return 1
    case .mentionsOnly: return 2
    case .paused: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [ParticipationMode] = [
    .unspecified,
    .speakFreely,
    .mentionsOnly,
    .paused,
  ]

}

/// ConversationCustomMetadata stores custom metadata for XMTP conversations
///
/// Encoding optimizations for compact storage:
/// - inboxId: Hex-decoded bytes (32 bytes) instead of hex string (64 chars) - saves ~32 bytes per member
/// - expiresAt: Unix sfixed64 (8 bytes) instead of protobuf Timestamp (10-16 bytes)
/// - DEFLATE compression applied if size >100 bytes (typically 20-40% reduction)
///
/// Image encryption (lean approach):
/// - One 32-byte AES-256 key per group (imageEncryptionKey)
/// - Per-image: URL + salt + nonce (no digest - AES-GCM auth tag provides integrity)
/// - ~48 bytes overhead per image
public nonisolated struct ConversationCustomMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var tag: String = String()

  public var profiles: [ConversationProfile] = []

  public var expiresAtUnix: Int64 {
    get {_expiresAtUnix ?? 0}
    set {_expiresAtUnix = newValue}
  }
  /// Returns true if `expiresAtUnix` has been explicitly set.
  public var hasExpiresAtUnix: Bool {self._expiresAtUnix != nil}
  /// Clears the value of `expiresAtUnix`. Subsequent reads from it will return its default value.
  public mutating func clearExpiresAtUnix() {self._expiresAtUnix = nil}

  /// 32-byte AES-256 key for encrypting all images
  public var imageEncryptionKey: Data {
    get {_imageEncryptionKey ?? Data()}
    set {_imageEncryptionKey = newValue}
  }
  /// Returns true if `imageEncryptionKey` has been explicitly set.
  public var hasImageEncryptionKey: Bool {self._imageEncryptionKey != nil}
  /// Clears the value of `imageEncryptionKey`. Subsequent reads from it will return its default value.
  public mutating func clearImageEncryptionKey() {self._imageEncryptionKey = nil}

  /// Encrypted group avatar
  public var encryptedGroupImage: EncryptedImageRef {
    get {_encryptedGroupImage ?? EncryptedImageRef()}
    set {_encryptedGroupImage = newValue}
  }
  /// Returns true if `encryptedGroupImage` has been explicitly set.
  public var hasEncryptedGroupImage: Bool {self._encryptedGroupImage != nil}
  /// Clears the value of `encryptedGroupImage`. Subsequent reads from it will return its default value.
  public mutating func clearEncryptedGroupImage() {self._encryptedGroupImage = nil}

  public var emoji: String {
    get {_emoji ?? String()}
    set {_emoji = newValue}
  }
  /// Returns true if `emoji` has been explicitly set.
  public var hasEmoji: Bool {self._emoji != nil}
  /// Clears the value of `emoji`. Subsequent reads from it will return its default value.
  public mutating func clearEmoji() {self._emoji = nil}

  /// Present when this conversation is a DM with an agent
  public var agentDm: AgentDmInfo {
    get {_agentDm ?? AgentDmInfo()}
    set {_agentDm = newValue}
  }
  /// Returns true if `agentDm` has been explicitly set.
  public var hasAgentDm: Bool {self._agentDm != nil}
  /// Clears the value of `agentDm`. Subsequent reads from it will return its default value.
  public mutating func clearAgentDm() {self._agentDm = nil}

  /// How much the conversation's agents may speak
  public var participationMode: ParticipationMode {
    get {_participationMode ?? .unspecified}
    set {_participationMode = newValue}
  }
  /// Returns true if `participationMode` has been explicitly set.
  public var hasParticipationMode: Bool {self._participationMode != nil}
  /// Clears the value of `participationMode`. Subsequent reads from it will return its default value.
  public mutating func clearParticipationMode() {self._participationMode = nil}

  /// Present when created as a 1:1 human DM (desktop mode)
  public var humanDm: HumanDmInfo {
    get {_humanDm ?? HumanDmInfo()}
    set {_humanDm = newValue}
  }
  /// Returns true if `humanDm` has been explicitly set.
  public var hasHumanDm: Bool {self._humanDm != nil}
  /// Clears the value of `humanDm`. Subsequent reads from it will return its default value.
  public mutating func clearHumanDm() {self._humanDm = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _expiresAtUnix: Int64? = nil
  fileprivate var _imageEncryptionKey: Data? = nil
  fileprivate var _encryptedGroupImage: EncryptedImageRef? = nil
  fileprivate var _emoji: String? = nil
  fileprivate var _agentDm: AgentDmInfo? = nil
  fileprivate var _participationMode: ParticipationMode? = nil
  fileprivate var _humanDm: HumanDmInfo? = nil
}

/// HumanDmInfo marks a conversation created via the contact/member "Chat" flow
/// as a human 1:1 DM. Presence-only provenance marker; clients only honor it
/// while the conversation has exactly 2 members and no verified agent member.
public nonisolated struct HumanDmInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// AgentDmInfo marks a 2-member conversation as a private DM with an agent.
/// The agent's identity comes from the membership itself (member_kind plus
/// attestation), not from this marker; clients only honor the marker when the
/// conversation has exactly 2 members and the other member is an agent.
public nonisolated struct AgentDmInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The primary group this DM was started from
  public var originConversationID: Data {
    get {_originConversationID ?? Data()}
    set {_originConversationID = newValue}
  }
  /// Returns true if `originConversationID` has been explicitly set.
  public var hasOriginConversationID: Bool {self._originConversationID != nil}
  /// Clears the value of `originConversationID`. Subsequent reads from it will return its default value.
  public mutating func clearOriginConversationID() {self._originConversationID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _originConversationID: Data? = nil
}

/// EncryptedImageRef stores encrypted image metadata
/// AES-GCM auth tag (16 bytes) is appended to ciphertext, providing integrity verification
public nonisolated struct EncryptedImageRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// S3 URL to encrypted ciphertext
  public var url: String = String()

  /// 32-byte HKDF salt for key derivation
  public var salt: Data = Data()

  /// 12-byte AES-GCM nonce
  public var nonce: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ConversationProfile represents a participant in the conversation
public nonisolated struct ConversationProfile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// XMTP inbox ID as hex-decoded bytes
  public var inboxID: Data = Data()

  public var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// Legacy: plain URL (backward compatibility)
  public var image: String {
    get {_image ?? String()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  /// New: encrypted image reference
  public var encryptedImage: EncryptedImageRef {
    get {_encryptedImage ?? EncryptedImageRef()}
    set {_encryptedImage = newValue}
  }
  /// Returns true if `encryptedImage` has been explicitly set.
  public var hasEncryptedImage: Bool {self._encryptedImage != nil}
  /// Clears the value of `encryptedImage`. Subsequent reads from it will return its default value.
  public mutating func clearEncryptedImage() {self._encryptedImage = nil}

  /// JSON grants payload for this sender's connections (see connections.mjs)
  public var connections: String {
    get {_connections ?? String()}
    set {_connections = newValue}
  }
  /// Returns true if `connections` has been explicitly set.
  public var hasConnections: Bool {self._connections != nil}
  /// Clears the value of `connections`. Subsequent reads from it will return its default value.
  public mutating func clearConnections() {self._connections = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _image: String? = nil
  fileprivate var _encryptedImage: EncryptedImageRef? = nil
  fileprivate var _connections: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension ParticipationMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PARTICIPATION_MODE_UNSPECIFIED\0\u{1}PARTICIPATION_MODE_SPEAK_FREELY\0\u{1}PARTICIPATION_MODE_MENTIONS_ONLY\0\u{2}\u{2}PARTICIPATION_MODE_PAUSED\0")
}

nonisolated extension ConversationCustomMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ConversationCustomMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tag\0\u{1}profiles\0\u{1}expiresAtUnix\0\u{1}imageEncryptionKey\0\u{1}encryptedGroupImage\0\u{1}emoji\0\u{2}\u{2}agentDm\0\u{1}participationMode\0\u{1}humanDm\0\u{c}\u{7}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.profiles) }()
      case 3: try { try decoder.decodeSingularSFixed64Field(value: &self._expiresAtUnix) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._imageEncryptionKey) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._encryptedGroupImage) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._emoji) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._agentDm) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._participationMode) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._humanDm) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 1)
    }
    if !self.profiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.profiles, fieldNumber: 2)
    }
    try { if let v = self._expiresAtUnix {
      try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._imageEncryptionKey {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._encryptedGroupImage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._emoji {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._agentDm {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._participationMode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._humanDm {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ConversationCustomMetadata, rhs: ConversationCustomMetadata) -> Bool {
    if lhs.tag != rhs.tag {return false}
    if lhs.profiles != rhs.profiles {return false}
    if lhs._expiresAtUnix != rhs._expiresAtUnix {return false}
    if lhs._imageEncryptionKey != rhs._imageEncryptionKey {return false}
    if lhs._encryptedGroupImage != rhs._encryptedGroupImage {return false}
    if lhs._emoji != rhs._emoji {return false}
    if lhs._agentDm != rhs._agentDm {return false}
    if lhs._participationMode != rhs._participationMode {return false}
    if lhs._humanDm != rhs._humanDm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension HumanDmInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "HumanDmInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: HumanDmInfo, rhs: HumanDmInfo) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension AgentDmInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AgentDmInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}originConversationId\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._originConversationID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._originConversationID {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AgentDmInfo, rhs: AgentDmInfo) -> Bool {
    if lhs._originConversationID != rhs._originConversationID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension EncryptedImageRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "EncryptedImageRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{1}salt\0\u{1}nonce\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.salt) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if !self.salt.isEmpty {
      try visitor.visitSingularBytesField(value: self.salt, fieldNumber: 2)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: EncryptedImageRef, rhs: EncryptedImageRef) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.salt != rhs.salt {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension ConversationProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ConversationProfile"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}inboxId\0\u{1}name\0\u{1}image\0\u{1}encryptedImage\0\u{1}connections\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.inboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._image) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._encryptedImage) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._connections) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.inboxID.isEmpty {
      try visitor.visitSingularBytesField(value: self.inboxID, fieldNumber: 1)
    }
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._image {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._encryptedImage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._connections {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ConversationProfile, rhs: ConversationProfile) -> Bool {
    if lhs.inboxID != rhs.inboxID {return false}
    if lhs._name != rhs._name {return false}
    if lhs._image != rhs._image {return false}
    if lhs._encryptedImage != rhs._encryptedImage {return false}
    if lhs._connections != rhs._connections {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
