#!/usr/bin/env bash

# Shared utility functions for secrets generation scripts

# Swift string escape function to prevent injection attacks
swift_escape() {
    local s="$1"
    s="${s//\\/\\\\}"      # Escape backslashes first
    s="${s//\"/\\\"}"      # Escape quotes
    s="${s//$'\n'/\\n}"    # Escape newlines
    s="${s//$'\t'/\\t}"    # Escape tabs
    s="${s//$'\r'/\\r}"    # Escape carriage returns
    printf '%s\n' "$s"
}

# Validate Swift identifier
is_valid_swift_identifier() {
    [[ "$1" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]
}

# Common header for generated Secrets.swift files
generate_secrets_header() {
    local generator_script="$1"
    cat <<EOF
import Foundation

// WARNING:
// This code is generated by $generator_script.
// Do not edit this file directly. Your changes will be lost on next run.
// Git does not track this file.
EOF
}

# Function to create directories for both targets
ensure_secrets_directories() {
    mkdir -p "Convos/Config"
    mkdir -p "ConvosAppClip/Config"
}

# Detect git commit SHA.
# Optional first argument: repo directory to cd into (use for Xcode build phases
# where the working directory is not the repo root). Omit for standalone scripts
# that already run from the repo root.
# Priority: $GITHUB_SHA -> $BITRISE_GIT_COMMIT -> git rev-parse -> "unknown"
get_git_commit_sha() {
    local repo_dir="${1:-}"
    local raw_sha="${GITHUB_SHA:-${BITRISE_GIT_COMMIT:-}}"
    if [ -z "$raw_sha" ]; then
        if [ -n "$repo_dir" ]; then
            (cd "$repo_dir" && git rev-parse --short HEAD 2>/dev/null) || echo "unknown"
        else
            git rev-parse --short HEAD 2>/dev/null || echo "unknown"
        fi
    else
        echo "${raw_sha:0:7}"
    fi
}
