// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: conversation_profile.proto

import Foundation
import SwiftProtobuf

// MARK: - EncryptedImageRef

/// EncryptedImageRef stores encrypted image metadata
/// AES-GCM auth tag (16 bytes) is appended to ciphertext, providing integrity verification
public struct EncryptedImageRef: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below.

    /// S3 URL to encrypted ciphertext
    public var url: String = String()

    /// 32-byte HKDF salt for key derivation
    public var salt: Data = Data()

    /// 12-byte AES-GCM nonce
    public var nonce: Data = Data()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - ConversationProfile

/// ConversationProfile represents a participant in the conversation
/// Stored in XMTP group appData as part of ConversationCustomMetadata
public struct ConversationProfile: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below.

    /// XMTP inbox ID as hex-decoded bytes (32 bytes)
    public var inboxID: Data = Data()

    public var name: String {
        get { _name ?? String() }
        set { _name = newValue }
    }

    /// Returns true if `name` has been explicitly set.
    public var hasName: Bool { _name != nil }
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    public mutating func clearName() { _name = nil }

    /// Legacy: plain URL (backward compatibility)
    public var image: String {
        get { _image ?? String() }
        set { _image = newValue }
    }

    /// Returns true if `image` has been explicitly set.
    public var hasImage: Bool { _image != nil }
    /// Clears the value of `image`. Subsequent reads from it will return its default value.
    public mutating func clearImage() { _image = nil }

    /// New: encrypted image reference
    public var encryptedImage: EncryptedImageRef {
        get { _encryptedImage ?? EncryptedImageRef() }
        set { _encryptedImage = newValue }
    }

    /// Returns true if `encryptedImage` has been explicitly set.
    public var hasEncryptedImage: Bool { _encryptedImage != nil }
    /// Clears the value of `encryptedImage`. Subsequent reads from it will return its default value.
    public mutating func clearEncryptedImage() { _encryptedImage = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _name: String?
    fileprivate var _image: String?
    fileprivate var _encryptedImage: EncryptedImageRef?
}

// MARK: - SwiftProtobuf Conformance

extension EncryptedImageRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = "EncryptedImageRef"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{01}url\0\u{01}salt\0\u{01}nonce\0")

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &url)
            case 2: try decoder.decodeSingularBytesField(value: &salt)
            case 3: try decoder.decodeSingularBytesField(value: &nonce)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !url.isEmpty {
            try visitor.visitSingularStringField(value: url, fieldNumber: 1)
        }
        if !salt.isEmpty {
            try visitor.visitSingularBytesField(value: salt, fieldNumber: 2)
        }
        if !nonce.isEmpty {
            try visitor.visitSingularBytesField(value: nonce, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: EncryptedImageRef, rhs: EncryptedImageRef) -> Bool {
        if lhs.url != rhs.url { return false }
        if lhs.salt != rhs.salt { return false }
        if lhs.nonce != rhs.nonce { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension ConversationProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = "ConversationProfile"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{01}inboxId\0\u{01}name\0\u{01}image\0\u{01}encryptedImage\0")

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularBytesField(value: &inboxID)
            case 2: try decoder.decodeSingularStringField(value: &_name)
            case 3: try decoder.decodeSingularStringField(value: &_image)
            case 4: try decoder.decodeSingularMessageField(value: &_encryptedImage)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !inboxID.isEmpty {
            try visitor.visitSingularBytesField(value: inboxID, fieldNumber: 1)
        }
        if let v = _name {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        if let v = _image {
            try visitor.visitSingularStringField(value: v, fieldNumber: 3)
        }
        if let v = _encryptedImage {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: ConversationProfile, rhs: ConversationProfile) -> Bool {
        if lhs.inboxID != rhs.inboxID { return false }
        if lhs._name != rhs._name { return false }
        if lhs._image != rhs._image { return false }
        if lhs._encryptedImage != rhs._encryptedImage { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
